# Generated by Django 4.1.4 on 2023-01-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
